In [379]:
#1. Create a DataFrame with Random Data
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(1, 101, size=(1000, 5)), columns=list('ABCDE'))
df.head()

    A   B   C   D   E
0  33  35  31  55  94
1  52  90  98  51  43
2  87  73  50  21  77
3  96  16  12  95  91
4  99  43   1  67  74

In [381]:
#2. Check for Missing Values
df.isnull().sum()

A    0
B    0
C    0
D    0
E    0
dtype: int64

In [383]:
#3. Fill Missing Values with Mean
df.fillna(df.mean(), inplace=True)
df.head()

    A   B   C   D   E
0  33  35  31  55  94
1  52  90  98  51  43
2  87  73  50  21  77
3  96  16  12  95  91
4  99  43   1  67  74

In [385]:
#4. Add a New Column as Sum of Two Columns
df['F'] = df['A'] + df['B']
df.head()

    A   B   C   D   E    F
0  33  35  31  55  94   68
1  52  90  98  51  43  142
2  87  73  50  21  77  160
3  96  16  12  95  91  112
4  99  43   1  67  74  142

In [387]:
#5. Rename Columns
df.rename(columns={'A':'Alpha', 'B':'Beta'}, inplace=True)
df.head()

   Alpha  Beta   C   D   E    F
0     33    35  31  55  94   68
1     52    90  98  51  43  142
2     87    73  50  21  77  160
3     96    16  12  95  91  112
4     99    43   1  67  74  142

In [389]:
#6. Replace Specific Values
df.replace({'C': {5, 50}}, inplace=True)
df.head()

   Alpha  Beta   C   D   E    F
0     33    35  31  55  94   68
1     52    90  98  51  43  142
2     87    73  50  21  77  160
3     96    16  12  95  91  112
4     99    43   1  67  74  142

In [391]:
#7. Drop Rows with Any NaN Values
df.dropna(inplace=True)
df.head()

   Alpha  Beta   C   D   E    F
0     33    35  31  55  94   68
1     52    90  98  51  43  142
2     87    73  50  21  77  160
3     96    16  12  95  91  112
4     99    43   1  67  74  142

In [393]:
#8. Sort DataFrame by a Column
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'D': [50, 20, 80, 30, 10]  # Sorting column
})

df.sort_values(by='D', ascending=False, inplace=True)
df.head()

   A   D
2  3  80
0  1  50
3  4  30
1  2  20
4  5  10

In [395]:
#9. Filter Rows Based on Condition
df = pd.DataFrame({
    'A': [10, 55, 30, 75, 100],
    'B': ['X', 'Y', 'Z', 'W', 'V']
})
filtered_df = df[df['A'] > 50]
filtered_df

     A  B
1   55  Y
3   75  W
4  100  V

In [397]:
#10. Select Specific Columns
df[['A', 'B']]

     A  B
0   10  X
1   55  Y
2   30  Z
3   75  W
4  100  V

In [399]:
#11. Group by and Sum
df.groupby('B').sum()

     A
B
V  100
W   75
X   10
Y   55
Z   30

In [401]:
#12. Count Unique Values per Group
df = pd.DataFrame({
    'B': ['X', 'X', 'Y', 'Y', 'Y', 'Z', 'Z', 'Z'],
    'C': [10, 20, 10, 10, 30, 20, 20, 40]
})
unique_counts = df.groupby('B')['C'].nunique()
unique_counts

B
X    2
Y    2
Z    2
Name: C, dtype: int64

In [403]:
#13. Maximum Value per Group
df = pd.DataFrame({
    'A': ['X', 'X', 'Y', 'Y', 'Y', 'Z', 'Z', 'Z'],
    'D': [10, 20, 30, 25, 50, 40, 15, 60]
})
max_values = df.groupby('A')['D'].max()
max_values

A
X    20
Y    50
Z    60
Name: D, dtype: int64

In [405]:
#14. Apply Custom Function
df = pd.DataFrame({
    'B': ['A', 'A', 'B', 'B', 'C', 'C', 'C'],
    'C': [10, 30, 50, 70, 20, 60, 100]
})
range_per_group = df.groupby('B')['C'].apply(lambda x: x.max() - x.min())
range_per_group

B
A    20
B    20
C    80
Name: C, dtype: int64

In [407]:
#15. Compute Rolling Mean
df = pd.DataFrame({'D': [10, 20, 30, 40, 50, 60, 70]})
df['D_rolling'] = df['D'].rolling(window=3).mean()
df.head()

    D  D_rolling
0  10        NaN
1  20        NaN
2  30       20.0
3  40       30.0
4  50       40.0

In [215]:
#16. Merge Two DataFrames on a Column
df1 = pd.DataFrame({'ID':[1,2,3], 'A':[10, 20, 30]})
df2 = pd.DataFrame({'ID':[1,2,4], 'B':[40, 50, 60]})
df_merged = pd.merge(df1, df2, on='ID', how='inner')
df_merged

   ID   A   B
0   1  10  40
1   2  20  50

In [217]:
#17. Concatenate DataFrames Row-Wise
df_concat = pd.concat([df1, df2], axis=0)
df_concat

   ID     A     B
0   1  10.0   NaN
1   2  20.0   NaN
2   3  30.0   NaN
0   1   NaN  40.0
1   2   NaN  50.0
2   4   NaN  60.0

In [415]:
#18. Find and Remove Duplicates
data = {
    'A': [1, 2, 2, 3, 4, 4, 5],
    'B': ['X', 'Y', 'Y', 'Z', 'X', 'X', 'Y']
}

df = pd.DataFrame(data)
dup = df.drop_duplicates(inplace=True)
df.head()

   A  B
0  1  X
1  2  Y
3  3  Z
4  4  X
6  5  Y

In [417]:
#19. Pivot Table Creation
data = {
    'A': ['X', 'X', 'Y', 'Y', 'Z', 'Z', 'X'],
    'B': ['M', 'N', 'M', 'N', 'M', 'N', 'M'],
    'D': [10, 20, 30, 40, 50, 60, 70]
}

df = pd.DataFrame(data)
pivot_df = df.pivot_table(values='D', index='A', columns='B', aggfunc='mean')
pivot_df

B     M     N
A
X  40.0  20.0
Y  30.0  40.0
Z  50.0  60.0

In [239]:
#20. Extract Year from Date Column
df=pd.DataFrame({'Date':['2023-05-15', '2019-06-12', '2018-07-13']})
df['Year']=pd.to_datetime(df['Date']).dt.year
df

         Date  Year
0  2023-05-15  2023
1  2019-06-12  2019
2  2018-07-13  2018

In [243]:
#21. Finding Outliers Using IQR
df=pd.DataFrame({'A':[10, 20, 30, 40, 50, 100, 200]})
Q1=df['A'].quantile(0.25)
Q3=df['A'].quantile(0.75)
IQR=Q3-Q1
outliers=df[(df['A']<(Q1-1.5*IQR)) | (df['A']>(Q3+1.5*IQR))]
outliers

     A
6  200

In [247]:
#22. Create a Multi-Index DataFrame
df=pd.DataFrame({'A': ['X', 'X', 'Y', 'Y'],
    'B': [1, 2, 1, 2],
    'C': [10, 20, 30, 40]
                })
df.set_index(['A', 'B'], inplace=True)
df

      C
A B
X 1  10
  2  20
Y 1  30
  2  40

In [257]:
#23. Resample Time Series Data
data = {
    'Date': pd.date_range(start='2024-01-01', periods=10, freq='D'),
    'Sales': [100, 200, 150, 300, 400, 250, 450, 600, 350, 500]
}
df = pd.DataFrame(data)
df.set_index('Date').resample('ME').mean()

            Sales
Date
2024-01-31  330.0

In [261]:
#24. Normalize a Column
df = pd.DataFrame({'C': [10, 20, 30, 40, 50]})
df['C_norm'] = (df['C'] - df['C'].min()) / (df['C'].max() - df['C'].min())
print(df)

    C  C_norm
0  10    0.00
1  20    0.25
2  30    0.50
3  40    0.75
4  50    1.00

In [269]:
#25. Encode Categorical Variables
df = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Category': ['A', 'B', 'A', 'C']
})
print(df)
df = pd.get_dummies(df, columns=['Category'])
print(df)

   ID Category
0   1        A
1   2        B
2   3        A
3   4        C
   ID  Category_A  Category_B  Category_C
0   1        True       False       False
1   2       False        True       False
2   3        True       False       False
3   4       False       False        True

In [271]:
#26. Finding Correlation Between Columns
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [2, 4, 6, 8, 10],
    'C': [5, 3, 2, 4, 1]
})
df.corr()

     A    B    C
A  1.0  1.0 -0.7
B  1.0  1.0 -0.7
C -0.7 -0.7  1.0

In [273]:
#27. Apply Custom Function to a Column
df = pd.DataFrame({'C': [10, 55, 40, 80, 25]})
df['C_transformed'] = df['C'].apply(lambda x: x * 2 if x > 50 else x / 2)
df.head()

    C  C_transformed
0  10            5.0
1  55          110.0
2  40           20.0
3  80          160.0
4  25           12.5

In [281]:
#28. Convert JSON Data to DataFrame
import json
from io import StringIO 
data = '{"A": [1, 2, 3], "B": [4, 5, 6]}'
df = pd.read_json(StringIO(data))
df.head()

   A  B
0  1  4
1  2  5
2  3  6

In [287]:
#29. Detect and Handle Skewed Data
df = pd.DataFrame({'A': [0, 1, 10, 100, 1000]})
df['A_log'] = np.log1p(df['A'])
df.head()

      A     A_log
0     0  0.000000
1     1  0.693147
2    10  2.397895
3   100  4.615121
4  1000  6.908755

In [291]:
#30. Split a Column into Multiple Columns
data = {'Full Name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown']}
df = pd.DataFrame(data)
df[['First', 'Second']] = df['Full Name'].str.split(' ', expand=True)
df.head()

       Full Name    First   Second
0  Alice Johnson    Alice  Johnson
1      Bob Smith      Bob    Smith
2  Charlie Brown  Charlie    Brown

In [295]:
#31. Convert Dictionary into DataFrame
data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data)
df.head()

   A  B
0  1  3
1  2  4

In [301]:
#32. Export DataFrame to CSV Without Index

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
df.to_csv('output.csv', index=False)
df.head()

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [437]:
#33. Read Large CSV in Chunks
for chunk in pd.read_csv('~/Desktop/myfile.txt', chunksize=1000):
    process(chunk)

Processing 3 rows
      Name   Age          City
0    Alice    25      New York
1      Bob    30   Los Angeles
2  Charlie    22       Chicago

In [309]:
#34. Find First Non-NaN Value in Each Column
data = {
    'A': [np.nan, np.nan, 3, 4],
    'B': [np.nan, 7, np.nan, 9],
    'C': [1, np.nan, np.nan, 8]
}

df = pd.DataFrame(data)
df.apply(lambda x: x.dropna().iloc[0])
df.head()

     A    B    C
0  NaN  NaN  1.0
1  NaN  7.0  NaN
2  3.0  NaN  NaN
3  4.0  9.0  8.0

In [311]:
#35. Use map() for Element-wise Transformations
data = {'D': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data)
df['D'] = df['D'].map(lambda x: x**2)
df.head()

    D
0   1
1   4
2   9
3  16
4  25

In [315]:
#36. Find Top 5 Frequent Values in a Column
data = {'C': [3, 1, 2, 3, 2, 3, 4, 1, 2, 2, 3, 4, 3, 2, 1]}
df = pd.DataFrame(data)
df['C'].value_counts().head(5)

C
3    5
2    5
1    3
4    2
Name: count, dtype: int64

In [319]:
#37. Calculate Running Total (Cumulative Sum)
data = {'A': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df['Cumulative_Sum'] = df['A'].cumsum()
df.head()

    A  Cumulative_Sum
0  10              10
1  20              30
2  30              60
3  40             100
4  50             150

In [445]:
#38. Apply a Weighted Mean Function
data = {
    'B': ['X', 'X', 'Y', 'Y', 'Y'],
    'A': [10, 20, 30, 40, 50],
    'C': [2, 3, 1, 4, 5]  # Weights
}
df = pd.DataFrame(data)
df.groupby('B').apply(lambda x: np.average(x['A'], weights=x['C']))
df.head()

/var/folders/7j/64n417ls4bxb_hrlb2nsxxr80000gq/T/ipykernel_19530/1380636476.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('B').apply(lambda x: np.average(x['A'], weights=x['C']))

   B   A  C
0  X  10  2
1  X  20  3
2  Y  30  1
3  Y  40  4
4  Y  50  5

In [439]:
#39. Fill Missing Values Using Forward Fill
data = {
    'A': [1, np.nan, np.nan, 4, 5],
    'B': [10, 20, np.nan, np.nan, 50]
}
df = pd.DataFrame(data)
df.ffill(inplace=True)
df.head()

     A     B
0  1.0  10.0
1  1.0  20.0
2  1.0  20.0
3  4.0  20.0
4  5.0  50.0

In [329]:
#40. Grouping by Multiple Columns and Applying Multiple Aggregations
data = {
    'A': ['X', 'X', 'Y', 'Y', 'Z', 'Z'],
    'B': [1, 1, 2, 2, 3, 3],
    'C': [10, 20, 30, 40, 50, 60],
    'D': [5, 15, 25, 35, 45, 55]
}

df = pd.DataFrame(data)
df.groupby(['A', 'B']).agg({'C': ['mean', 'sum'], 'D': ['max', 'min']})
df.head()

   A  B   C   D
0  X  1  10   5
1  X  1  20  15
2  Y  2  30  25
3  Y  2  40  35
4  Z  3  50  45

In [333]:
#41. Creating a Custom Aggregation Function for GroupBy
data = {
    'B': ['X', 'X', 'Y', 'Y', 'Z', 'Z'],
    'A': [10, 20, 30, 40, 50, 60],
    'C': [5, 15, 25, 35, 45, 55]
}

df = pd.DataFrame(data)
df.groupby('B').agg(lambda x: x.median() - x.mean())
df.head()

   B   A   C
0  X  10   5
1  X  20  15
2  Y  30  25
3  Y  40  35
4  Z  50  45

In [337]:
#42. Applying a Custom Sorting Order on a Column
data = {
    'Task': ['Task A', 'Task B', 'Task C', 'Task D'],
    'Priority': ['Medium', 'High', 'Low', 'High']
}

df = pd.DataFrame(data)
custom_order = {'Low': 1, 'Medium': 2, 'High': 3}
df['Priority'] = df['Priority'].map(custom_order)
df.sort_values(by='Priority', inplace=True)
df.head()

     Task  Priority
2  Task C         1
0  Task A         2
1  Task B         3
3  Task D         3

In [339]:
#43. Finding the Largest 3 Values in Each Column
data = {
    'A': [10, 50, 30, 70, 90],
    'B': [15, 65, 45, 85, 25],
    'C': [5, 55, 35, 75, 95]
}

df = pd.DataFrame(data)
df.apply(lambda x: x.nlargest(3).values)
df.head()

    A   B   C
0  10  15   5
1  50  65  55
2  30  45  35
3  70  85  75
4  90  25  95

In [349]:
#44. Checking if Any Column has Negative Values
data = {
    'A': [10, -5, 30, -2, 90],
    'B': [15, 65, -45, 85, 25],
    'C': [5, 55, 35, 75, 95]
}

df = pd.DataFrame(data)
df.lt(0).any()

A     True
B     True
C    False
dtype: bool

In [351]:
#45. Finding the Most Frequent Value in Each Column
data = {
    'A': [10, 20, 10, 30, 10],
    'B': [5, 5, 15, 5, 25],
    'C': [100, 200, 100, 300, 100]
}

df = pd.DataFrame(data)
df.mode().iloc[0]

A     10
B      5
C    100
Name: 0, dtype: int64

In [359]:
#46. Detecting Duplicate Rows in a DataFrame
data = {
    'A': [10, 20, 10, 30, 10],
    'B': [5, 5, 15, 5, 25],
    'C': [100, 200, 100, 300, 100]
}

df = pd.DataFrame(data)
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [363]:
#47. Extracting Hour from a Timestamp
data = {
    'Timestamp': ['2024-04-03 08:15:00', '2024-04-03 14:30:00', '2024-04-03 22:45:00']
}

df = pd.DataFrame(data)
df['Hour'] = pd.to_datetime(df['Timestamp']).dt.hour
df.head()

             Timestamp  Hour
0  2024-04-03 08:15:00     8
1  2024-04-03 14:30:00    14
2  2024-04-03 22:45:00    22

In [369]:
#48. Finding All Rows with a Specific Pattern in a Column
data = {
    'Name': ['John Doe', 'Alice Smith', 'Johnny Bravo', 'Mike Johnson', None],
    'Age': [28, 34, 40, 23, 29]
}
df = pd.DataFrame(data)
result = df[df['Name'].str.contains('John', case=False, na=False)]
print(result)

           Name  Age
0      John Doe   28
2  Johnny Bravo   40
3  Mike Johnson   23

In [371]:
#49. Converting a Column with Strings to Numeric Values
data = {'Amount': ['100', '200.5', '300', 'Invalid', '400']}
df = pd.DataFrame(data)
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')
df

   Amount
0   100.0
1   200.5
2   300.0
3     NaN
4   400.0

In [377]:
#50. Reshaping DataFrame from Wide to Long Format
df = pd.DataFrame({
    'ID': [1, 2, 3],
    'Math': [85, 90, 78],
    'Science': [92, 88, 95],
    'English': [80, 85, 88]
})
df_long = df.melt(id_vars=['ID'], var_name='Feature', value_name='Value')
df_long

   ID  Feature  Value
0   1     Math     85
1   2     Math     90
2   3     Math     78
3   1  Science     92
4   2  Science     88
5   3  Science     95
6   1  English     80
7   2  English     85
8   3  English     88